// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_refbox_log.proto

package Protobuf;

public final class MessagesRobocupSslRefboxLog {
  private MessagesRobocupSslRefboxLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Log_FrameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .SSL_DetectionFrame frame = 1;
    boolean hasFrame();
    MessagesRobocupSslDetection.SSL_DetectionFrame getFrame();
    MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder();
    
    // required string refbox_cmd = 2;
    boolean hasRefboxCmd();
    String getRefboxCmd();
  }
  public static final class Log_Frame extends
      com.google.protobuf.GeneratedMessage
      implements Log_FrameOrBuilder {
    // Use Log_Frame.newBuilder() to construct.
    private Log_Frame(Builder builder) {
      super(builder);
    }
    private Log_Frame(boolean noInit) {}
    
    private static final Log_Frame defaultInstance;
    public static Log_Frame getDefaultInstance() {
      return defaultInstance;
    }
    
    public Log_Frame getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagesRobocupSslRefboxLog.internal_static_Log_Frame_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .SSL_DetectionFrame frame = 1;
    public static final int FRAME_FIELD_NUMBER = 1;
    private MessagesRobocupSslDetection.SSL_DetectionFrame frame_;
    public boolean hasFrame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public MessagesRobocupSslDetection.SSL_DetectionFrame getFrame() {
      return frame_;
    }
    public MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder() {
      return frame_;
    }
    
    // required string refbox_cmd = 2;
    public static final int REFBOX_CMD_FIELD_NUMBER = 2;
    private java.lang.Object refboxCmd_;
    public boolean hasRefboxCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getRefboxCmd() {
      java.lang.Object ref = refboxCmd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          refboxCmd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRefboxCmdBytes() {
      java.lang.Object ref = refboxCmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        refboxCmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
      refboxCmd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFrame()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefboxCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFrame().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, frame_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRefboxCmdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, frame_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRefboxCmdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Log_Frame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessagesRobocupSslRefboxLog.Log_Frame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MessagesRobocupSslRefboxLog.Log_FrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagesRobocupSslRefboxLog.internal_static_Log_Frame_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagesRobocupSslRefboxLog.internal_static_Log_Frame_fieldAccessorTable;
      }
      
      // Construct using MessagesRobocupSslRefboxLog.Log_Frame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFrameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (frameBuilder_ == null) {
          frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
        } else {
          frameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        refboxCmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagesRobocupSslRefboxLog.Log_Frame.getDescriptor();
      }
      
      public MessagesRobocupSslRefboxLog.Log_Frame getDefaultInstanceForType() {
        return MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance();
      }
      
      public MessagesRobocupSslRefboxLog.Log_Frame build() {
        MessagesRobocupSslRefboxLog.Log_Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private MessagesRobocupSslRefboxLog.Log_Frame buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        MessagesRobocupSslRefboxLog.Log_Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public MessagesRobocupSslRefboxLog.Log_Frame buildPartial() {
        MessagesRobocupSslRefboxLog.Log_Frame result = new MessagesRobocupSslRefboxLog.Log_Frame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (frameBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = frameBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.refboxCmd_ = refboxCmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagesRobocupSslRefboxLog.Log_Frame) {
          return mergeFrom((MessagesRobocupSslRefboxLog.Log_Frame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessagesRobocupSslRefboxLog.Log_Frame other) {
        if (other == MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance()) return this;
        if (other.hasFrame()) {
          mergeFrame(other.getFrame());
        }
        if (other.hasRefboxCmd()) {
          setRefboxCmd(other.getRefboxCmd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFrame()) {
          
          return false;
        }
        if (!hasRefboxCmd()) {
          
          return false;
        }
        if (!getFrame().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              MessagesRobocupSslDetection.SSL_DetectionFrame.Builder subBuilder = MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder();
              if (hasFrame()) {
                subBuilder.mergeFrom(getFrame());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFrame(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              refboxCmd_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .SSL_DetectionFrame frame = 1;
      private MessagesRobocupSslDetection.SSL_DetectionFrame frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> frameBuilder_;
      public boolean hasFrame() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public MessagesRobocupSslDetection.SSL_DetectionFrame getFrame() {
        if (frameBuilder_ == null) {
          return frame_;
        } else {
          return frameBuilder_.getMessage();
        }
      }
      public Builder setFrame(MessagesRobocupSslDetection.SSL_DetectionFrame value) {
        if (frameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          frame_ = value;
          onChanged();
        } else {
          frameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setFrame(
          MessagesRobocupSslDetection.SSL_DetectionFrame.Builder builderForValue) {
        if (frameBuilder_ == null) {
          frame_ = builderForValue.build();
          onChanged();
        } else {
          frameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeFrame(MessagesRobocupSslDetection.SSL_DetectionFrame value) {
        if (frameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              frame_ != MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance()) {
            frame_ =
              MessagesRobocupSslDetection.SSL_DetectionFrame.newBuilder(frame_).mergeFrom(value).buildPartial();
          } else {
            frame_ = value;
          }
          onChanged();
        } else {
          frameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearFrame() {
        if (frameBuilder_ == null) {
          frame_ = MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance();
          onChanged();
        } else {
          frameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public MessagesRobocupSslDetection.SSL_DetectionFrame.Builder getFrameBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFrameFieldBuilder().getBuilder();
      }
      public MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getFrameOrBuilder() {
        if (frameBuilder_ != null) {
          return frameBuilder_.getMessageOrBuilder();
        } else {
          return frame_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> 
          getFrameFieldBuilder() {
        if (frameBuilder_ == null) {
          frameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              MessagesRobocupSslDetection.SSL_DetectionFrame, MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder>(
                  frame_,
                  getParentForChildren(),
                  isClean());
          frame_ = null;
        }
        return frameBuilder_;
      }
      
      // required string refbox_cmd = 2;
      private java.lang.Object refboxCmd_ = "";
      public boolean hasRefboxCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getRefboxCmd() {
        java.lang.Object ref = refboxCmd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          refboxCmd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRefboxCmd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        refboxCmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearRefboxCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        refboxCmd_ = getDefaultInstance().getRefboxCmd();
        onChanged();
        return this;
      }
      void setRefboxCmd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        refboxCmd_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Log_Frame)
    }
    
    static {
      defaultInstance = new Log_Frame(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Log_Frame)
  }
  
  public interface Refbox_LogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .Log_Frame log = 1;
    java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> 
        getLogList();
    MessagesRobocupSslRefboxLog.Log_Frame getLog(int index);
    int getLogCount();
    java.util.List<? extends MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> 
        getLogOrBuilderList();
    MessagesRobocupSslRefboxLog.Log_FrameOrBuilder getLogOrBuilder(
        int index);
  }
  public static final class Refbox_Log extends
      com.google.protobuf.GeneratedMessage
      implements Refbox_LogOrBuilder {
    // Use Refbox_Log.newBuilder() to construct.
    private Refbox_Log(Builder builder) {
      super(builder);
    }
    private Refbox_Log(boolean noInit) {}
    
    private static final Refbox_Log defaultInstance;
    public static Refbox_Log getDefaultInstance() {
      return defaultInstance;
    }
    
    public Refbox_Log getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_fieldAccessorTable;
    }
    
    // repeated .Log_Frame log = 1;
    public static final int LOG_FIELD_NUMBER = 1;
    private java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> log_;
    public java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> getLogList() {
      return log_;
    }
    public java.util.List<? extends MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> 
        getLogOrBuilderList() {
      return log_;
    }
    public int getLogCount() {
      return log_.size();
    }
    public MessagesRobocupSslRefboxLog.Log_Frame getLog(int index) {
      return log_.get(index);
    }
    public MessagesRobocupSslRefboxLog.Log_FrameOrBuilder getLogOrBuilder(
        int index) {
      return log_.get(index);
    }
    
    private void initFields() {
      log_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getLogCount(); i++) {
        if (!getLog(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < log_.size(); i++) {
        output.writeMessage(1, log_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < log_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, log_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessagesRobocupSslRefboxLog.Refbox_Log parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessagesRobocupSslRefboxLog.Refbox_Log prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MessagesRobocupSslRefboxLog.Refbox_LogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagesRobocupSslRefboxLog.internal_static_Refbox_Log_fieldAccessorTable;
      }
      
      // Construct using MessagesRobocupSslRefboxLog.Refbox_Log.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (logBuilder_ == null) {
          log_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          logBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagesRobocupSslRefboxLog.Refbox_Log.getDescriptor();
      }
      
      public MessagesRobocupSslRefboxLog.Refbox_Log getDefaultInstanceForType() {
        return MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance();
      }
      
      public MessagesRobocupSslRefboxLog.Refbox_Log build() {
        MessagesRobocupSslRefboxLog.Refbox_Log result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private MessagesRobocupSslRefboxLog.Refbox_Log buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        MessagesRobocupSslRefboxLog.Refbox_Log result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public MessagesRobocupSslRefboxLog.Refbox_Log buildPartial() {
        MessagesRobocupSslRefboxLog.Refbox_Log result = new MessagesRobocupSslRefboxLog.Refbox_Log(this);
        int from_bitField0_ = bitField0_;
        if (logBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            log_ = java.util.Collections.unmodifiableList(log_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.log_ = log_;
        } else {
          result.log_ = logBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagesRobocupSslRefboxLog.Refbox_Log) {
          return mergeFrom((MessagesRobocupSslRefboxLog.Refbox_Log)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessagesRobocupSslRefboxLog.Refbox_Log other) {
        if (other == MessagesRobocupSslRefboxLog.Refbox_Log.getDefaultInstance()) return this;
        if (logBuilder_ == null) {
          if (!other.log_.isEmpty()) {
            if (log_.isEmpty()) {
              log_ = other.log_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLogIsMutable();
              log_.addAll(other.log_);
            }
            onChanged();
          }
        } else {
          if (!other.log_.isEmpty()) {
            if (logBuilder_.isEmpty()) {
              logBuilder_.dispose();
              logBuilder_ = null;
              log_ = other.log_;
              bitField0_ = (bitField0_ & ~0x00000001);
              logBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLogFieldBuilder() : null;
            } else {
              logBuilder_.addAllMessages(other.log_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getLogCount(); i++) {
          if (!getLog(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              MessagesRobocupSslRefboxLog.Log_Frame.Builder subBuilder = MessagesRobocupSslRefboxLog.Log_Frame.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLog(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .Log_Frame log = 1;
      private java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> log_ =
        java.util.Collections.emptyList();
      private void ensureLogIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          log_ = new java.util.ArrayList<MessagesRobocupSslRefboxLog.Log_Frame>(log_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          MessagesRobocupSslRefboxLog.Log_Frame, MessagesRobocupSslRefboxLog.Log_Frame.Builder, MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> logBuilder_;
      
      public java.util.List<MessagesRobocupSslRefboxLog.Log_Frame> getLogList() {
        if (logBuilder_ == null) {
          return java.util.Collections.unmodifiableList(log_);
        } else {
          return logBuilder_.getMessageList();
        }
      }
      public int getLogCount() {
        if (logBuilder_ == null) {
          return log_.size();
        } else {
          return logBuilder_.getCount();
        }
      }
      public MessagesRobocupSslRefboxLog.Log_Frame getLog(int index) {
        if (logBuilder_ == null) {
          return log_.get(index);
        } else {
          return logBuilder_.getMessage(index);
        }
      }
      public Builder setLog(
          int index, MessagesRobocupSslRefboxLog.Log_Frame value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.set(index, value);
          onChanged();
        } else {
          logBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLog(
          int index, MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.set(index, builderForValue.build());
          onChanged();
        } else {
          logBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLog(MessagesRobocupSslRefboxLog.Log_Frame value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.add(value);
          onChanged();
        } else {
          logBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLog(
          int index, MessagesRobocupSslRefboxLog.Log_Frame value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogIsMutable();
          log_.add(index, value);
          onChanged();
        } else {
          logBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLog(
          MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.add(builderForValue.build());
          onChanged();
        } else {
          logBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLog(
          int index, MessagesRobocupSslRefboxLog.Log_Frame.Builder builderForValue) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.add(index, builderForValue.build());
          onChanged();
        } else {
          logBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLog(
          java.lang.Iterable<? extends MessagesRobocupSslRefboxLog.Log_Frame> values) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          super.addAll(values, log_);
          onChanged();
        } else {
          logBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLog() {
        if (logBuilder_ == null) {
          log_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          logBuilder_.clear();
        }
        return this;
      }
      public Builder removeLog(int index) {
        if (logBuilder_ == null) {
          ensureLogIsMutable();
          log_.remove(index);
          onChanged();
        } else {
          logBuilder_.remove(index);
        }
        return this;
      }
      public MessagesRobocupSslRefboxLog.Log_Frame.Builder getLogBuilder(
          int index) {
        return getLogFieldBuilder().getBuilder(index);
      }
      public MessagesRobocupSslRefboxLog.Log_FrameOrBuilder getLogOrBuilder(
          int index) {
        if (logBuilder_ == null) {
          return log_.get(index);  } else {
          return logBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> 
           getLogOrBuilderList() {
        if (logBuilder_ != null) {
          return logBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(log_);
        }
      }
      public MessagesRobocupSslRefboxLog.Log_Frame.Builder addLogBuilder() {
        return getLogFieldBuilder().addBuilder(
            MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance());
      }
      public MessagesRobocupSslRefboxLog.Log_Frame.Builder addLogBuilder(
          int index) {
        return getLogFieldBuilder().addBuilder(
            index, MessagesRobocupSslRefboxLog.Log_Frame.getDefaultInstance());
      }
      public java.util.List<MessagesRobocupSslRefboxLog.Log_Frame.Builder> 
           getLogBuilderList() {
        return getLogFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          MessagesRobocupSslRefboxLog.Log_Frame, MessagesRobocupSslRefboxLog.Log_Frame.Builder, MessagesRobocupSslRefboxLog.Log_FrameOrBuilder> 
          getLogFieldBuilder() {
        if (logBuilder_ == null) {
          logBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              MessagesRobocupSslRefboxLog.Log_Frame, MessagesRobocupSslRefboxLog.Log_Frame.Builder, MessagesRobocupSslRefboxLog.Log_FrameOrBuilder>(
                  log_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          log_ = null;
        }
        return logBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Refbox_Log)
    }
    
    static {
      defaultInstance = new Refbox_Log(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Refbox_Log)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Log_Frame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Log_Frame_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Refbox_Log_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Refbox_Log_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%messages_robocup_ssl_refbox_log.proto\032" +
      "$messages_robocup_ssl_detection.proto\"C\n" +
      "\tLog_Frame\022\"\n\005frame\030\001 \002(\0132\023.SSL_Detectio" +
      "nFrame\022\022\n\nrefbox_cmd\030\002 \002(\t\"%\n\nRefbox_Log" +
      "\022\027\n\003log\030\001 \003(\0132\n.Log_Frame"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Log_Frame_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Log_Frame_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Log_Frame_descriptor,
              new java.lang.String[] { "Frame", "RefboxCmd", },
              MessagesRobocupSslRefboxLog.Log_Frame.class,
              MessagesRobocupSslRefboxLog.Log_Frame.Builder.class);
          internal_static_Refbox_Log_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Refbox_Log_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Refbox_Log_descriptor,
              new java.lang.String[] { "Log", },
              MessagesRobocupSslRefboxLog.Refbox_Log.class,
              MessagesRobocupSslRefboxLog.Refbox_Log.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MessagesRobocupSslDetection.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
