// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grSim_Packet.proto

#ifndef PROTOBUF_grSim_5fPacket_2eproto__INCLUDED
#define PROTOBUF_grSim_5fPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "grSim_Commands.pb.h"
#include "grSim_Replacement.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_grSim_5fPacket_2eproto();
void protobuf_AssignDesc_grSim_5fPacket_2eproto();
void protobuf_ShutdownFile_grSim_5fPacket_2eproto();

class grSim_Packet;

// ===================================================================

class grSim_Packet : public ::google::protobuf::Message {
 public:
  grSim_Packet();
  virtual ~grSim_Packet();
  
  grSim_Packet(const grSim_Packet& from);
  
  inline grSim_Packet& operator=(const grSim_Packet& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const grSim_Packet& default_instance();
  
  void Swap(grSim_Packet* other);
  
  // implements Message ----------------------------------------------
  
  grSim_Packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const grSim_Packet& from);
  void MergeFrom(const grSim_Packet& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .grSim_Commands commands = 1;
  inline bool has_commands() const;
  inline void clear_commands();
  static const int kCommandsFieldNumber = 1;
  inline const ::grSim_Commands& commands() const;
  inline ::grSim_Commands* mutable_commands();
  inline ::grSim_Commands* release_commands();
  
  // optional .grSim_Replacement replacement = 2;
  inline bool has_replacement() const;
  inline void clear_replacement();
  static const int kReplacementFieldNumber = 2;
  inline const ::grSim_Replacement& replacement() const;
  inline ::grSim_Replacement* mutable_replacement();
  inline ::grSim_Replacement* release_replacement();
  
  // @@protoc_insertion_point(class_scope:grSim_Packet)
 private:
  inline void set_has_commands();
  inline void clear_has_commands();
  inline void set_has_replacement();
  inline void clear_has_replacement();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::grSim_Commands* commands_;
  ::grSim_Replacement* replacement_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_grSim_5fPacket_2eproto();
  friend void protobuf_AssignDesc_grSim_5fPacket_2eproto();
  friend void protobuf_ShutdownFile_grSim_5fPacket_2eproto();
  
  void InitAsDefaultInstance();
  static grSim_Packet* default_instance_;
};
// ===================================================================


// ===================================================================

// grSim_Packet

// optional .grSim_Commands commands = 1;
inline bool grSim_Packet::has_commands() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void grSim_Packet::set_has_commands() {
  _has_bits_[0] |= 0x00000001u;
}
inline void grSim_Packet::clear_has_commands() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void grSim_Packet::clear_commands() {
  if (commands_ != NULL) commands_->::grSim_Commands::Clear();
  clear_has_commands();
}
inline const ::grSim_Commands& grSim_Packet::commands() const {
  return commands_ != NULL ? *commands_ : *default_instance_->commands_;
}
inline ::grSim_Commands* grSim_Packet::mutable_commands() {
  set_has_commands();
  if (commands_ == NULL) commands_ = new ::grSim_Commands;
  return commands_;
}
inline ::grSim_Commands* grSim_Packet::release_commands() {
  clear_has_commands();
  ::grSim_Commands* temp = commands_;
  commands_ = NULL;
  return temp;
}

// optional .grSim_Replacement replacement = 2;
inline bool grSim_Packet::has_replacement() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void grSim_Packet::set_has_replacement() {
  _has_bits_[0] |= 0x00000002u;
}
inline void grSim_Packet::clear_has_replacement() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void grSim_Packet::clear_replacement() {
  if (replacement_ != NULL) replacement_->::grSim_Replacement::Clear();
  clear_has_replacement();
}
inline const ::grSim_Replacement& grSim_Packet::replacement() const {
  return replacement_ != NULL ? *replacement_ : *default_instance_->replacement_;
}
inline ::grSim_Replacement* grSim_Packet::mutable_replacement() {
  set_has_replacement();
  if (replacement_ == NULL) replacement_ = new ::grSim_Replacement;
  return replacement_;
}
inline ::grSim_Replacement* grSim_Packet::release_replacement() {
  clear_has_replacement();
  ::grSim_Replacement* temp = replacement_;
  replacement_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_grSim_5fPacket_2eproto__INCLUDED
