// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_geometry.proto

#ifndef PROTOBUF_messages_5frobocup_5fssl_5fgeometry_2eproto__INCLUDED
#define PROTOBUF_messages_5frobocup_5fssl_5fgeometry_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();

class SSL_GeometryFieldSize;
class SSL_GeometryCameraCalibration;
class SSL_GeometryData;

// ===================================================================

class SSL_GeometryFieldSize : public ::google::protobuf::Message {
 public:
  SSL_GeometryFieldSize();
  virtual ~SSL_GeometryFieldSize();
  
  SSL_GeometryFieldSize(const SSL_GeometryFieldSize& from);
  
  inline SSL_GeometryFieldSize& operator=(const SSL_GeometryFieldSize& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_GeometryFieldSize& default_instance();
  
  void Swap(SSL_GeometryFieldSize* other);
  
  // implements Message ----------------------------------------------
  
  SSL_GeometryFieldSize* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_GeometryFieldSize& from);
  void MergeFrom(const SSL_GeometryFieldSize& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 line_width = 1;
  inline bool has_line_width() const;
  inline void clear_line_width();
  static const int kLineWidthFieldNumber = 1;
  inline ::google::protobuf::int32 line_width() const;
  inline void set_line_width(::google::protobuf::int32 value);
  
  // required int32 field_length = 2;
  inline bool has_field_length() const;
  inline void clear_field_length();
  static const int kFieldLengthFieldNumber = 2;
  inline ::google::protobuf::int32 field_length() const;
  inline void set_field_length(::google::protobuf::int32 value);
  
  // required int32 field_width = 3;
  inline bool has_field_width() const;
  inline void clear_field_width();
  static const int kFieldWidthFieldNumber = 3;
  inline ::google::protobuf::int32 field_width() const;
  inline void set_field_width(::google::protobuf::int32 value);
  
  // required int32 boundary_width = 4;
  inline bool has_boundary_width() const;
  inline void clear_boundary_width();
  static const int kBoundaryWidthFieldNumber = 4;
  inline ::google::protobuf::int32 boundary_width() const;
  inline void set_boundary_width(::google::protobuf::int32 value);
  
  // required int32 referee_width = 5;
  inline bool has_referee_width() const;
  inline void clear_referee_width();
  static const int kRefereeWidthFieldNumber = 5;
  inline ::google::protobuf::int32 referee_width() const;
  inline void set_referee_width(::google::protobuf::int32 value);
  
  // required int32 goal_width = 6;
  inline bool has_goal_width() const;
  inline void clear_goal_width();
  static const int kGoalWidthFieldNumber = 6;
  inline ::google::protobuf::int32 goal_width() const;
  inline void set_goal_width(::google::protobuf::int32 value);
  
  // required int32 goal_depth = 7;
  inline bool has_goal_depth() const;
  inline void clear_goal_depth();
  static const int kGoalDepthFieldNumber = 7;
  inline ::google::protobuf::int32 goal_depth() const;
  inline void set_goal_depth(::google::protobuf::int32 value);
  
  // required int32 goal_wall_width = 8;
  inline bool has_goal_wall_width() const;
  inline void clear_goal_wall_width();
  static const int kGoalWallWidthFieldNumber = 8;
  inline ::google::protobuf::int32 goal_wall_width() const;
  inline void set_goal_wall_width(::google::protobuf::int32 value);
  
  // required int32 center_circle_radius = 9;
  inline bool has_center_circle_radius() const;
  inline void clear_center_circle_radius();
  static const int kCenterCircleRadiusFieldNumber = 9;
  inline ::google::protobuf::int32 center_circle_radius() const;
  inline void set_center_circle_radius(::google::protobuf::int32 value);
  
  // required int32 defense_radius = 10;
  inline bool has_defense_radius() const;
  inline void clear_defense_radius();
  static const int kDefenseRadiusFieldNumber = 10;
  inline ::google::protobuf::int32 defense_radius() const;
  inline void set_defense_radius(::google::protobuf::int32 value);
  
  // required int32 defense_stretch = 11;
  inline bool has_defense_stretch() const;
  inline void clear_defense_stretch();
  static const int kDefenseStretchFieldNumber = 11;
  inline ::google::protobuf::int32 defense_stretch() const;
  inline void set_defense_stretch(::google::protobuf::int32 value);
  
  // required int32 free_kick_from_defense_dist = 12;
  inline bool has_free_kick_from_defense_dist() const;
  inline void clear_free_kick_from_defense_dist();
  static const int kFreeKickFromDefenseDistFieldNumber = 12;
  inline ::google::protobuf::int32 free_kick_from_defense_dist() const;
  inline void set_free_kick_from_defense_dist(::google::protobuf::int32 value);
  
  // required int32 penalty_spot_from_field_line_dist = 13;
  inline bool has_penalty_spot_from_field_line_dist() const;
  inline void clear_penalty_spot_from_field_line_dist();
  static const int kPenaltySpotFromFieldLineDistFieldNumber = 13;
  inline ::google::protobuf::int32 penalty_spot_from_field_line_dist() const;
  inline void set_penalty_spot_from_field_line_dist(::google::protobuf::int32 value);
  
  // required int32 penalty_line_from_spot_dist = 14;
  inline bool has_penalty_line_from_spot_dist() const;
  inline void clear_penalty_line_from_spot_dist();
  static const int kPenaltyLineFromSpotDistFieldNumber = 14;
  inline ::google::protobuf::int32 penalty_line_from_spot_dist() const;
  inline void set_penalty_line_from_spot_dist(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:SSL_GeometryFieldSize)
 private:
  inline void set_has_line_width();
  inline void clear_has_line_width();
  inline void set_has_field_length();
  inline void clear_has_field_length();
  inline void set_has_field_width();
  inline void clear_has_field_width();
  inline void set_has_boundary_width();
  inline void clear_has_boundary_width();
  inline void set_has_referee_width();
  inline void clear_has_referee_width();
  inline void set_has_goal_width();
  inline void clear_has_goal_width();
  inline void set_has_goal_depth();
  inline void clear_has_goal_depth();
  inline void set_has_goal_wall_width();
  inline void clear_has_goal_wall_width();
  inline void set_has_center_circle_radius();
  inline void clear_has_center_circle_radius();
  inline void set_has_defense_radius();
  inline void clear_has_defense_radius();
  inline void set_has_defense_stretch();
  inline void clear_has_defense_stretch();
  inline void set_has_free_kick_from_defense_dist();
  inline void clear_has_free_kick_from_defense_dist();
  inline void set_has_penalty_spot_from_field_line_dist();
  inline void clear_has_penalty_spot_from_field_line_dist();
  inline void set_has_penalty_line_from_spot_dist();
  inline void clear_has_penalty_line_from_spot_dist();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 line_width_;
  ::google::protobuf::int32 field_length_;
  ::google::protobuf::int32 field_width_;
  ::google::protobuf::int32 boundary_width_;
  ::google::protobuf::int32 referee_width_;
  ::google::protobuf::int32 goal_width_;
  ::google::protobuf::int32 goal_depth_;
  ::google::protobuf::int32 goal_wall_width_;
  ::google::protobuf::int32 center_circle_radius_;
  ::google::protobuf::int32 defense_radius_;
  ::google::protobuf::int32 defense_stretch_;
  ::google::protobuf::int32 free_kick_from_defense_dist_;
  ::google::protobuf::int32 penalty_spot_from_field_line_dist_;
  ::google::protobuf::int32 penalty_line_from_spot_dist_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(14 + 31) / 32];
  
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();
  
  void InitAsDefaultInstance();
  static SSL_GeometryFieldSize* default_instance_;
};
// -------------------------------------------------------------------

class SSL_GeometryCameraCalibration : public ::google::protobuf::Message {
 public:
  SSL_GeometryCameraCalibration();
  virtual ~SSL_GeometryCameraCalibration();
  
  SSL_GeometryCameraCalibration(const SSL_GeometryCameraCalibration& from);
  
  inline SSL_GeometryCameraCalibration& operator=(const SSL_GeometryCameraCalibration& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_GeometryCameraCalibration& default_instance();
  
  void Swap(SSL_GeometryCameraCalibration* other);
  
  // implements Message ----------------------------------------------
  
  SSL_GeometryCameraCalibration* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_GeometryCameraCalibration& from);
  void MergeFrom(const SSL_GeometryCameraCalibration& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 camera_id = 1;
  inline bool has_camera_id() const;
  inline void clear_camera_id();
  static const int kCameraIdFieldNumber = 1;
  inline ::google::protobuf::uint32 camera_id() const;
  inline void set_camera_id(::google::protobuf::uint32 value);
  
  // required float focal_length = 2;
  inline bool has_focal_length() const;
  inline void clear_focal_length();
  static const int kFocalLengthFieldNumber = 2;
  inline float focal_length() const;
  inline void set_focal_length(float value);
  
  // required float principal_point_x = 3;
  inline bool has_principal_point_x() const;
  inline void clear_principal_point_x();
  static const int kPrincipalPointXFieldNumber = 3;
  inline float principal_point_x() const;
  inline void set_principal_point_x(float value);
  
  // required float principal_point_y = 4;
  inline bool has_principal_point_y() const;
  inline void clear_principal_point_y();
  static const int kPrincipalPointYFieldNumber = 4;
  inline float principal_point_y() const;
  inline void set_principal_point_y(float value);
  
  // required float distortion = 5;
  inline bool has_distortion() const;
  inline void clear_distortion();
  static const int kDistortionFieldNumber = 5;
  inline float distortion() const;
  inline void set_distortion(float value);
  
  // required float q0 = 6;
  inline bool has_q0() const;
  inline void clear_q0();
  static const int kQ0FieldNumber = 6;
  inline float q0() const;
  inline void set_q0(float value);
  
  // required float q1 = 7;
  inline bool has_q1() const;
  inline void clear_q1();
  static const int kQ1FieldNumber = 7;
  inline float q1() const;
  inline void set_q1(float value);
  
  // required float q2 = 8;
  inline bool has_q2() const;
  inline void clear_q2();
  static const int kQ2FieldNumber = 8;
  inline float q2() const;
  inline void set_q2(float value);
  
  // required float q3 = 9;
  inline bool has_q3() const;
  inline void clear_q3();
  static const int kQ3FieldNumber = 9;
  inline float q3() const;
  inline void set_q3(float value);
  
  // required float tx = 10;
  inline bool has_tx() const;
  inline void clear_tx();
  static const int kTxFieldNumber = 10;
  inline float tx() const;
  inline void set_tx(float value);
  
  // required float ty = 11;
  inline bool has_ty() const;
  inline void clear_ty();
  static const int kTyFieldNumber = 11;
  inline float ty() const;
  inline void set_ty(float value);
  
  // required float tz = 12;
  inline bool has_tz() const;
  inline void clear_tz();
  static const int kTzFieldNumber = 12;
  inline float tz() const;
  inline void set_tz(float value);
  
  // optional float derived_camera_world_tx = 13;
  inline bool has_derived_camera_world_tx() const;
  inline void clear_derived_camera_world_tx();
  static const int kDerivedCameraWorldTxFieldNumber = 13;
  inline float derived_camera_world_tx() const;
  inline void set_derived_camera_world_tx(float value);
  
  // optional float derived_camera_world_ty = 14;
  inline bool has_derived_camera_world_ty() const;
  inline void clear_derived_camera_world_ty();
  static const int kDerivedCameraWorldTyFieldNumber = 14;
  inline float derived_camera_world_ty() const;
  inline void set_derived_camera_world_ty(float value);
  
  // optional float derived_camera_world_tz = 15;
  inline bool has_derived_camera_world_tz() const;
  inline void clear_derived_camera_world_tz();
  static const int kDerivedCameraWorldTzFieldNumber = 15;
  inline float derived_camera_world_tz() const;
  inline void set_derived_camera_world_tz(float value);
  
  // @@protoc_insertion_point(class_scope:SSL_GeometryCameraCalibration)
 private:
  inline void set_has_camera_id();
  inline void clear_has_camera_id();
  inline void set_has_focal_length();
  inline void clear_has_focal_length();
  inline void set_has_principal_point_x();
  inline void clear_has_principal_point_x();
  inline void set_has_principal_point_y();
  inline void clear_has_principal_point_y();
  inline void set_has_distortion();
  inline void clear_has_distortion();
  inline void set_has_q0();
  inline void clear_has_q0();
  inline void set_has_q1();
  inline void clear_has_q1();
  inline void set_has_q2();
  inline void clear_has_q2();
  inline void set_has_q3();
  inline void clear_has_q3();
  inline void set_has_tx();
  inline void clear_has_tx();
  inline void set_has_ty();
  inline void clear_has_ty();
  inline void set_has_tz();
  inline void clear_has_tz();
  inline void set_has_derived_camera_world_tx();
  inline void clear_has_derived_camera_world_tx();
  inline void set_has_derived_camera_world_ty();
  inline void clear_has_derived_camera_world_ty();
  inline void set_has_derived_camera_world_tz();
  inline void clear_has_derived_camera_world_tz();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 camera_id_;
  float focal_length_;
  float principal_point_x_;
  float principal_point_y_;
  float distortion_;
  float q0_;
  float q1_;
  float q2_;
  float q3_;
  float tx_;
  float ty_;
  float tz_;
  float derived_camera_world_tx_;
  float derived_camera_world_ty_;
  float derived_camera_world_tz_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(15 + 31) / 32];
  
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();
  
  void InitAsDefaultInstance();
  static SSL_GeometryCameraCalibration* default_instance_;
};
// -------------------------------------------------------------------

class SSL_GeometryData : public ::google::protobuf::Message {
 public:
  SSL_GeometryData();
  virtual ~SSL_GeometryData();
  
  SSL_GeometryData(const SSL_GeometryData& from);
  
  inline SSL_GeometryData& operator=(const SSL_GeometryData& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_GeometryData& default_instance();
  
  void Swap(SSL_GeometryData* other);
  
  // implements Message ----------------------------------------------
  
  SSL_GeometryData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_GeometryData& from);
  void MergeFrom(const SSL_GeometryData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .SSL_GeometryFieldSize field = 1;
  inline bool has_field() const;
  inline void clear_field();
  static const int kFieldFieldNumber = 1;
  inline const ::SSL_GeometryFieldSize& field() const;
  inline ::SSL_GeometryFieldSize* mutable_field();
  inline ::SSL_GeometryFieldSize* release_field();
  
  // repeated .SSL_GeometryCameraCalibration calib = 2;
  inline int calib_size() const;
  inline void clear_calib();
  static const int kCalibFieldNumber = 2;
  inline const ::SSL_GeometryCameraCalibration& calib(int index) const;
  inline ::SSL_GeometryCameraCalibration* mutable_calib(int index);
  inline ::SSL_GeometryCameraCalibration* add_calib();
  inline const ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >&
      calib() const;
  inline ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >*
      mutable_calib();
  
  // @@protoc_insertion_point(class_scope:SSL_GeometryData)
 private:
  inline void set_has_field();
  inline void clear_has_field();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::SSL_GeometryFieldSize* field_;
  ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > calib_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();
  
  void InitAsDefaultInstance();
  static SSL_GeometryData* default_instance_;
};
// ===================================================================


// ===================================================================

// SSL_GeometryFieldSize

// required int32 line_width = 1;
inline bool SSL_GeometryFieldSize::has_line_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_line_width() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_GeometryFieldSize::clear_has_line_width() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_GeometryFieldSize::clear_line_width() {
  line_width_ = 0;
  clear_has_line_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::line_width() const {
  return line_width_;
}
inline void SSL_GeometryFieldSize::set_line_width(::google::protobuf::int32 value) {
  set_has_line_width();
  line_width_ = value;
}

// required int32 field_length = 2;
inline bool SSL_GeometryFieldSize::has_field_length() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_field_length() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SSL_GeometryFieldSize::clear_has_field_length() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SSL_GeometryFieldSize::clear_field_length() {
  field_length_ = 0;
  clear_has_field_length();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::field_length() const {
  return field_length_;
}
inline void SSL_GeometryFieldSize::set_field_length(::google::protobuf::int32 value) {
  set_has_field_length();
  field_length_ = value;
}

// required int32 field_width = 3;
inline bool SSL_GeometryFieldSize::has_field_width() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_field_width() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SSL_GeometryFieldSize::clear_has_field_width() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SSL_GeometryFieldSize::clear_field_width() {
  field_width_ = 0;
  clear_has_field_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::field_width() const {
  return field_width_;
}
inline void SSL_GeometryFieldSize::set_field_width(::google::protobuf::int32 value) {
  set_has_field_width();
  field_width_ = value;
}

// required int32 boundary_width = 4;
inline bool SSL_GeometryFieldSize::has_boundary_width() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_boundary_width() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SSL_GeometryFieldSize::clear_has_boundary_width() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SSL_GeometryFieldSize::clear_boundary_width() {
  boundary_width_ = 0;
  clear_has_boundary_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::boundary_width() const {
  return boundary_width_;
}
inline void SSL_GeometryFieldSize::set_boundary_width(::google::protobuf::int32 value) {
  set_has_boundary_width();
  boundary_width_ = value;
}

// required int32 referee_width = 5;
inline bool SSL_GeometryFieldSize::has_referee_width() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_referee_width() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SSL_GeometryFieldSize::clear_has_referee_width() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SSL_GeometryFieldSize::clear_referee_width() {
  referee_width_ = 0;
  clear_has_referee_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::referee_width() const {
  return referee_width_;
}
inline void SSL_GeometryFieldSize::set_referee_width(::google::protobuf::int32 value) {
  set_has_referee_width();
  referee_width_ = value;
}

// required int32 goal_width = 6;
inline bool SSL_GeometryFieldSize::has_goal_width() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_goal_width() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SSL_GeometryFieldSize::clear_has_goal_width() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SSL_GeometryFieldSize::clear_goal_width() {
  goal_width_ = 0;
  clear_has_goal_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::goal_width() const {
  return goal_width_;
}
inline void SSL_GeometryFieldSize::set_goal_width(::google::protobuf::int32 value) {
  set_has_goal_width();
  goal_width_ = value;
}

// required int32 goal_depth = 7;
inline bool SSL_GeometryFieldSize::has_goal_depth() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_goal_depth() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SSL_GeometryFieldSize::clear_has_goal_depth() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SSL_GeometryFieldSize::clear_goal_depth() {
  goal_depth_ = 0;
  clear_has_goal_depth();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::goal_depth() const {
  return goal_depth_;
}
inline void SSL_GeometryFieldSize::set_goal_depth(::google::protobuf::int32 value) {
  set_has_goal_depth();
  goal_depth_ = value;
}

// required int32 goal_wall_width = 8;
inline bool SSL_GeometryFieldSize::has_goal_wall_width() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_goal_wall_width() {
  _has_bits_[0] |= 0x00000080u;
}
inline void SSL_GeometryFieldSize::clear_has_goal_wall_width() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void SSL_GeometryFieldSize::clear_goal_wall_width() {
  goal_wall_width_ = 0;
  clear_has_goal_wall_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::goal_wall_width() const {
  return goal_wall_width_;
}
inline void SSL_GeometryFieldSize::set_goal_wall_width(::google::protobuf::int32 value) {
  set_has_goal_wall_width();
  goal_wall_width_ = value;
}

// required int32 center_circle_radius = 9;
inline bool SSL_GeometryFieldSize::has_center_circle_radius() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_center_circle_radius() {
  _has_bits_[0] |= 0x00000100u;
}
inline void SSL_GeometryFieldSize::clear_has_center_circle_radius() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void SSL_GeometryFieldSize::clear_center_circle_radius() {
  center_circle_radius_ = 0;
  clear_has_center_circle_radius();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::center_circle_radius() const {
  return center_circle_radius_;
}
inline void SSL_GeometryFieldSize::set_center_circle_radius(::google::protobuf::int32 value) {
  set_has_center_circle_radius();
  center_circle_radius_ = value;
}

// required int32 defense_radius = 10;
inline bool SSL_GeometryFieldSize::has_defense_radius() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_defense_radius() {
  _has_bits_[0] |= 0x00000200u;
}
inline void SSL_GeometryFieldSize::clear_has_defense_radius() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void SSL_GeometryFieldSize::clear_defense_radius() {
  defense_radius_ = 0;
  clear_has_defense_radius();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::defense_radius() const {
  return defense_radius_;
}
inline void SSL_GeometryFieldSize::set_defense_radius(::google::protobuf::int32 value) {
  set_has_defense_radius();
  defense_radius_ = value;
}

// required int32 defense_stretch = 11;
inline bool SSL_GeometryFieldSize::has_defense_stretch() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_defense_stretch() {
  _has_bits_[0] |= 0x00000400u;
}
inline void SSL_GeometryFieldSize::clear_has_defense_stretch() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void SSL_GeometryFieldSize::clear_defense_stretch() {
  defense_stretch_ = 0;
  clear_has_defense_stretch();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::defense_stretch() const {
  return defense_stretch_;
}
inline void SSL_GeometryFieldSize::set_defense_stretch(::google::protobuf::int32 value) {
  set_has_defense_stretch();
  defense_stretch_ = value;
}

// required int32 free_kick_from_defense_dist = 12;
inline bool SSL_GeometryFieldSize::has_free_kick_from_defense_dist() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_free_kick_from_defense_dist() {
  _has_bits_[0] |= 0x00000800u;
}
inline void SSL_GeometryFieldSize::clear_has_free_kick_from_defense_dist() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void SSL_GeometryFieldSize::clear_free_kick_from_defense_dist() {
  free_kick_from_defense_dist_ = 0;
  clear_has_free_kick_from_defense_dist();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::free_kick_from_defense_dist() const {
  return free_kick_from_defense_dist_;
}
inline void SSL_GeometryFieldSize::set_free_kick_from_defense_dist(::google::protobuf::int32 value) {
  set_has_free_kick_from_defense_dist();
  free_kick_from_defense_dist_ = value;
}

// required int32 penalty_spot_from_field_line_dist = 13;
inline bool SSL_GeometryFieldSize::has_penalty_spot_from_field_line_dist() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_penalty_spot_from_field_line_dist() {
  _has_bits_[0] |= 0x00001000u;
}
inline void SSL_GeometryFieldSize::clear_has_penalty_spot_from_field_line_dist() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void SSL_GeometryFieldSize::clear_penalty_spot_from_field_line_dist() {
  penalty_spot_from_field_line_dist_ = 0;
  clear_has_penalty_spot_from_field_line_dist();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::penalty_spot_from_field_line_dist() const {
  return penalty_spot_from_field_line_dist_;
}
inline void SSL_GeometryFieldSize::set_penalty_spot_from_field_line_dist(::google::protobuf::int32 value) {
  set_has_penalty_spot_from_field_line_dist();
  penalty_spot_from_field_line_dist_ = value;
}

// required int32 penalty_line_from_spot_dist = 14;
inline bool SSL_GeometryFieldSize::has_penalty_line_from_spot_dist() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_penalty_line_from_spot_dist() {
  _has_bits_[0] |= 0x00002000u;
}
inline void SSL_GeometryFieldSize::clear_has_penalty_line_from_spot_dist() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void SSL_GeometryFieldSize::clear_penalty_line_from_spot_dist() {
  penalty_line_from_spot_dist_ = 0;
  clear_has_penalty_line_from_spot_dist();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::penalty_line_from_spot_dist() const {
  return penalty_line_from_spot_dist_;
}
inline void SSL_GeometryFieldSize::set_penalty_line_from_spot_dist(::google::protobuf::int32 value) {
  set_has_penalty_line_from_spot_dist();
  penalty_line_from_spot_dist_ = value;
}

// -------------------------------------------------------------------

// SSL_GeometryCameraCalibration

// required uint32 camera_id = 1;
inline bool SSL_GeometryCameraCalibration::has_camera_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_camera_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_GeometryCameraCalibration::clear_has_camera_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_GeometryCameraCalibration::clear_camera_id() {
  camera_id_ = 0u;
  clear_has_camera_id();
}
inline ::google::protobuf::uint32 SSL_GeometryCameraCalibration::camera_id() const {
  return camera_id_;
}
inline void SSL_GeometryCameraCalibration::set_camera_id(::google::protobuf::uint32 value) {
  set_has_camera_id();
  camera_id_ = value;
}

// required float focal_length = 2;
inline bool SSL_GeometryCameraCalibration::has_focal_length() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_focal_length() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SSL_GeometryCameraCalibration::clear_has_focal_length() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SSL_GeometryCameraCalibration::clear_focal_length() {
  focal_length_ = 0;
  clear_has_focal_length();
}
inline float SSL_GeometryCameraCalibration::focal_length() const {
  return focal_length_;
}
inline void SSL_GeometryCameraCalibration::set_focal_length(float value) {
  set_has_focal_length();
  focal_length_ = value;
}

// required float principal_point_x = 3;
inline bool SSL_GeometryCameraCalibration::has_principal_point_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_principal_point_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SSL_GeometryCameraCalibration::clear_has_principal_point_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SSL_GeometryCameraCalibration::clear_principal_point_x() {
  principal_point_x_ = 0;
  clear_has_principal_point_x();
}
inline float SSL_GeometryCameraCalibration::principal_point_x() const {
  return principal_point_x_;
}
inline void SSL_GeometryCameraCalibration::set_principal_point_x(float value) {
  set_has_principal_point_x();
  principal_point_x_ = value;
}

// required float principal_point_y = 4;
inline bool SSL_GeometryCameraCalibration::has_principal_point_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_principal_point_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SSL_GeometryCameraCalibration::clear_has_principal_point_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SSL_GeometryCameraCalibration::clear_principal_point_y() {
  principal_point_y_ = 0;
  clear_has_principal_point_y();
}
inline float SSL_GeometryCameraCalibration::principal_point_y() const {
  return principal_point_y_;
}
inline void SSL_GeometryCameraCalibration::set_principal_point_y(float value) {
  set_has_principal_point_y();
  principal_point_y_ = value;
}

// required float distortion = 5;
inline bool SSL_GeometryCameraCalibration::has_distortion() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_distortion() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SSL_GeometryCameraCalibration::clear_has_distortion() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SSL_GeometryCameraCalibration::clear_distortion() {
  distortion_ = 0;
  clear_has_distortion();
}
inline float SSL_GeometryCameraCalibration::distortion() const {
  return distortion_;
}
inline void SSL_GeometryCameraCalibration::set_distortion(float value) {
  set_has_distortion();
  distortion_ = value;
}

// required float q0 = 6;
inline bool SSL_GeometryCameraCalibration::has_q0() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_q0() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SSL_GeometryCameraCalibration::clear_has_q0() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SSL_GeometryCameraCalibration::clear_q0() {
  q0_ = 0;
  clear_has_q0();
}
inline float SSL_GeometryCameraCalibration::q0() const {
  return q0_;
}
inline void SSL_GeometryCameraCalibration::set_q0(float value) {
  set_has_q0();
  q0_ = value;
}

// required float q1 = 7;
inline bool SSL_GeometryCameraCalibration::has_q1() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_q1() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SSL_GeometryCameraCalibration::clear_has_q1() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SSL_GeometryCameraCalibration::clear_q1() {
  q1_ = 0;
  clear_has_q1();
}
inline float SSL_GeometryCameraCalibration::q1() const {
  return q1_;
}
inline void SSL_GeometryCameraCalibration::set_q1(float value) {
  set_has_q1();
  q1_ = value;
}

// required float q2 = 8;
inline bool SSL_GeometryCameraCalibration::has_q2() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_q2() {
  _has_bits_[0] |= 0x00000080u;
}
inline void SSL_GeometryCameraCalibration::clear_has_q2() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void SSL_GeometryCameraCalibration::clear_q2() {
  q2_ = 0;
  clear_has_q2();
}
inline float SSL_GeometryCameraCalibration::q2() const {
  return q2_;
}
inline void SSL_GeometryCameraCalibration::set_q2(float value) {
  set_has_q2();
  q2_ = value;
}

// required float q3 = 9;
inline bool SSL_GeometryCameraCalibration::has_q3() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_q3() {
  _has_bits_[0] |= 0x00000100u;
}
inline void SSL_GeometryCameraCalibration::clear_has_q3() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void SSL_GeometryCameraCalibration::clear_q3() {
  q3_ = 0;
  clear_has_q3();
}
inline float SSL_GeometryCameraCalibration::q3() const {
  return q3_;
}
inline void SSL_GeometryCameraCalibration::set_q3(float value) {
  set_has_q3();
  q3_ = value;
}

// required float tx = 10;
inline bool SSL_GeometryCameraCalibration::has_tx() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_tx() {
  _has_bits_[0] |= 0x00000200u;
}
inline void SSL_GeometryCameraCalibration::clear_has_tx() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void SSL_GeometryCameraCalibration::clear_tx() {
  tx_ = 0;
  clear_has_tx();
}
inline float SSL_GeometryCameraCalibration::tx() const {
  return tx_;
}
inline void SSL_GeometryCameraCalibration::set_tx(float value) {
  set_has_tx();
  tx_ = value;
}

// required float ty = 11;
inline bool SSL_GeometryCameraCalibration::has_ty() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_ty() {
  _has_bits_[0] |= 0x00000400u;
}
inline void SSL_GeometryCameraCalibration::clear_has_ty() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void SSL_GeometryCameraCalibration::clear_ty() {
  ty_ = 0;
  clear_has_ty();
}
inline float SSL_GeometryCameraCalibration::ty() const {
  return ty_;
}
inline void SSL_GeometryCameraCalibration::set_ty(float value) {
  set_has_ty();
  ty_ = value;
}

// required float tz = 12;
inline bool SSL_GeometryCameraCalibration::has_tz() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_tz() {
  _has_bits_[0] |= 0x00000800u;
}
inline void SSL_GeometryCameraCalibration::clear_has_tz() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void SSL_GeometryCameraCalibration::clear_tz() {
  tz_ = 0;
  clear_has_tz();
}
inline float SSL_GeometryCameraCalibration::tz() const {
  return tz_;
}
inline void SSL_GeometryCameraCalibration::set_tz(float value) {
  set_has_tz();
  tz_ = value;
}

// optional float derived_camera_world_tx = 13;
inline bool SSL_GeometryCameraCalibration::has_derived_camera_world_tx() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_derived_camera_world_tx() {
  _has_bits_[0] |= 0x00001000u;
}
inline void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tx() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void SSL_GeometryCameraCalibration::clear_derived_camera_world_tx() {
  derived_camera_world_tx_ = 0;
  clear_has_derived_camera_world_tx();
}
inline float SSL_GeometryCameraCalibration::derived_camera_world_tx() const {
  return derived_camera_world_tx_;
}
inline void SSL_GeometryCameraCalibration::set_derived_camera_world_tx(float value) {
  set_has_derived_camera_world_tx();
  derived_camera_world_tx_ = value;
}

// optional float derived_camera_world_ty = 14;
inline bool SSL_GeometryCameraCalibration::has_derived_camera_world_ty() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_derived_camera_world_ty() {
  _has_bits_[0] |= 0x00002000u;
}
inline void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_ty() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void SSL_GeometryCameraCalibration::clear_derived_camera_world_ty() {
  derived_camera_world_ty_ = 0;
  clear_has_derived_camera_world_ty();
}
inline float SSL_GeometryCameraCalibration::derived_camera_world_ty() const {
  return derived_camera_world_ty_;
}
inline void SSL_GeometryCameraCalibration::set_derived_camera_world_ty(float value) {
  set_has_derived_camera_world_ty();
  derived_camera_world_ty_ = value;
}

// optional float derived_camera_world_tz = 15;
inline bool SSL_GeometryCameraCalibration::has_derived_camera_world_tz() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_derived_camera_world_tz() {
  _has_bits_[0] |= 0x00004000u;
}
inline void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tz() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void SSL_GeometryCameraCalibration::clear_derived_camera_world_tz() {
  derived_camera_world_tz_ = 0;
  clear_has_derived_camera_world_tz();
}
inline float SSL_GeometryCameraCalibration::derived_camera_world_tz() const {
  return derived_camera_world_tz_;
}
inline void SSL_GeometryCameraCalibration::set_derived_camera_world_tz(float value) {
  set_has_derived_camera_world_tz();
  derived_camera_world_tz_ = value;
}

// -------------------------------------------------------------------

// SSL_GeometryData

// required .SSL_GeometryFieldSize field = 1;
inline bool SSL_GeometryData::has_field() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_GeometryData::set_has_field() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_GeometryData::clear_has_field() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_GeometryData::clear_field() {
  if (field_ != NULL) field_->::SSL_GeometryFieldSize::Clear();
  clear_has_field();
}
inline const ::SSL_GeometryFieldSize& SSL_GeometryData::field() const {
  return field_ != NULL ? *field_ : *default_instance_->field_;
}
inline ::SSL_GeometryFieldSize* SSL_GeometryData::mutable_field() {
  set_has_field();
  if (field_ == NULL) field_ = new ::SSL_GeometryFieldSize;
  return field_;
}
inline ::SSL_GeometryFieldSize* SSL_GeometryData::release_field() {
  clear_has_field();
  ::SSL_GeometryFieldSize* temp = field_;
  field_ = NULL;
  return temp;
}

// repeated .SSL_GeometryCameraCalibration calib = 2;
inline int SSL_GeometryData::calib_size() const {
  return calib_.size();
}
inline void SSL_GeometryData::clear_calib() {
  calib_.Clear();
}
inline const ::SSL_GeometryCameraCalibration& SSL_GeometryData::calib(int index) const {
  return calib_.Get(index);
}
inline ::SSL_GeometryCameraCalibration* SSL_GeometryData::mutable_calib(int index) {
  return calib_.Mutable(index);
}
inline ::SSL_GeometryCameraCalibration* SSL_GeometryData::add_calib() {
  return calib_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >&
SSL_GeometryData::calib() const {
  return calib_;
}
inline ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >*
SSL_GeometryData::mutable_calib() {
  return &calib_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_5frobocup_5fssl_5fgeometry_2eproto__INCLUDED
